// Generated by CoffeeScript 1.6.3
(function() {
  var BROWSER, EDITOR, LAPTOP, MONITER27, MOVIE, REFERENCE, TERMINAL, WIKI, all_hide, apps, focuses, hash, hides, move, operation, operations;

  EDITOR = "Emacs";

  BROWSER = "Safari";

  MOVIE = "Movist";

  WIKI = "Notes";

  REFERENCE = "TextMate";

  TERMINAL = "iTerm";

  slate.bind("0:ctrl", slate.operation("relaunch"));

  MONITER27 = "2560x1440";

  LAPTOP = "1920x1200";

  apps = ["iTerm", "Emacs", "OmniFocus", "Google Chrome", "Things", "iTunes", "Preview", "QuickTime Player", "Safari", "Firefox", "Parallels Desktop", "Image Capture", "VietOCR", "Markdown Pro"];

  move = function(rx, ry, rw, rh, screen) {
    var h, w, x, y;
    if (screen == null) {
      screen = MONITER27;
    }
    x = "screenOriginX + screenSizeX * " + rx;
    y = "screenOriginY + screenSizeY * " + ry;
    w = "screenSizeX * " + rw;
    h = "screenSizeY * " + rh;
    return slate.operation("move", {
      "x": x,
      "y": y,
      "width": w,
      "height": h,
      "screen": screen
    });
  };

  all_hide = function() {
    return hides(apps);
  };

  operation = function(app, op) {
    return slate.operation(op, {
      "app": app
    });
  };

  operations = function(names, op) {
    var name, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = names.length; _i < _len; _i++) {
      name = names[_i];
      _results.push(operation(name, op));
    }
    return _results;
  };

  hides = function(names) {
    return operations(names, "hide");
  };

  focuses = function(names) {
    return operations(names, "focus");
  };

  hash = {};

  hash["_before_"] = {
    "operations": all_hide()
  };

  hash["_after_"] = {
    "operations": focuses([TERMINAL, EDITOR])
  };

  hash[EDITOR] = {
    "operations": [move(0, 0, 0.649, 1)]
  };

  hash[TERMINAL] = {
    "operations": [move(0.65, 0, 0.35, 1)]
  };

  hash[BROWSER] = {
    "operations": [move(0.65, 0, 0.35, 1)]
  };

  hash[REFERENCE] = {
    "operations": [move(0, 0, 0.499, 1, LAPTOP)]
  };

  hash[WIKI] = {
    "operations": [move(0.5, 0, 0.5, 1, LAPTOP)]
  };

  slate.layout("devel-terminal-2", hash);

  slate.bind("1:ctrl", slate.operation("layout", {
    "name": "devel-terminal-2"
  }));

  hash["_before_"] = {};

  hash["_after_"] = {
    "operations": focuses([BROWSER, EDITOR])
  };

  slate.layout("devel-safari-2", hash);

  slate.bind("2:ctrl", slate.operation("layout", {
    "name": "devel-safari-2"
  }));

}).call(this);
